apiVersion: v1
kind: Service
metadata:
  name: s3-event-logger
  labels:
    app: s3-event-logger
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: s3-event-logger
